### ISSUE TITLE
cal/locfli: symlinks to non existent paths

### ISSUE THREAD

**Issue by sfgraves** [Starlink/ORAC-DR#11]
ORAC-DR/cal/lcofli/lcogt_propid.txt
is a symlink to:
/data/tlister/SVN/LCO_Pipeline/trunk/code/oracdr/cal/lcosbig/lcogt_propid.txt

and 
ORAC-DR/cal/lcofli/proposal_list
is a symlink to

/data/tlister/SVN/LCO_Pipeline/trunk/code/oracdr/cal/lcosbig/proposal_list

I think these files should probably either be properly committed or removed from the source tree?

**Comment by talister** [comment]
On 01/14/2015 04:27 PM, Sarah Graves wrote:
> ORAC-DR/cal/lcofli/lcogt_propid.txt
> is a symlink to:
> /data/tlister/SVN/LCO_Pipeline/trunk/code/oracdr/cal/lcosbig/lcogt_propid.txt
>
> and
> ORAC-DR/cal/lcofli/proposal_list
> is a symlink to
>
> /data/tlister/SVN/LCO_Pipeline/trunk/code/oracdr/cal/lcosbig/proposal_list
>
> I think these files should probably either be properly committed or
> removed from the source tree?

Oops, those should definitely be removed. These are symlinks to dynamic 
snapshots of our valid proposal codes.

TimL

>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Starlink/ORAC-DR/issues/11>.
>


-- 
Dr Tim Lister
Astronomer and Project Scientist
Las Cumbres Observatory (LCOGT.net)
+1 805 880 1989

**Comment by talister** [comment]
Think they should be gone now.

**Comment by sfgraves** [comment]
Thanks, thats perfect.
